import type { TocEntry } from "./labs-toc";

/**
 * Static brief manifest — mirrors labs-static.ts pattern.
 *
 * Phase 7.4 fix applied: dynamic MDX imports break under OpenNext/Workers
 * (the bundler doesn't follow dynamic `import("../path.mdx")` so modules
 * aren't shipped). The brief identity + metadata layer is encoded as a TS
 * module the bundler tree-shakes and ships. Per-slug static imports live in
 * `src/app/citation-brief/[slug]/page.tsx`.
 *
 * Adding a new brief:
 *   1. Drop the .mdx into `src/content/citation-briefs/`
 *   2. Add a static import in `src/app/citation-brief/[slug]/page.tsx`
 *   3. Add an entry to BRIEF_MANIFEST below
 *   4. Add the slug to BRIEF_TOC if you want a TOC sidebar (optional)
 *
 * Removing a brief:
 *   1. Delete the .mdx
 *   2. Remove the entry below (or set hidden: true)
 *   3. Remove the static import in [slug]/page.tsx
 */

export type CitationBriefFaq = {
  question: string;
  answer: string;
};

export type CitationBriefManifestEntry = {
  slug: string;
  /** Sequential brief number. Padded to 3 digits for display + schema IDs. */
  briefNumber: number;
  title: string;
  summary: string;
  /** Badge label shown after "Citation Brief #NNN · ". */
  eyebrow: string;
  /** Article schema's articleSection. Often === eyebrow but separable. */
  category: string;
  author: string;
  reviewer: string;
  /** ISO date YYYY-MM-DD — matches the publication / last-update value. */
  lastUpdated: string;
  /** Optional OG image override; defaults to siteConfig.ogImage. */
  ogImage?: string;
  /** Mirrors hidden: true semantics — excluded from sitemap + index. */
  hidden?: boolean;
  /** Optional FAQ array — also drives FAQPage JSON-LD. */
  faq?: readonly CitationBriefFaq[];
  /** Estimated reading minutes (rounded). */
  readingMinutes: number;
};

export const BRIEF_MANIFEST: readonly CitationBriefManifestEntry[] = [
  {
    slug: "how-agencies-get-cited-in-ai-answers",
    briefNumber: 1,
    title:
      "How premium agencies get cited by ChatGPT, Perplexity, and Google AI Overviews",
    summary:
      "The Five-Stage Citation Hierarchy AI answer engines use, the signals that move the needle, and how to engineer for inclusion. Citation, not clicks.",
    eyebrow: "AEO methodology",
    category: "AEO methodology",
    author: "Jonathan Landman",
    reviewer: "Jonathan Landman",
    lastUpdated: "2026-05-14",
    readingMinutes: 12,
    // v3.9.3 P1a — brief-specific OG card (obsidian + electric Chromaglass).
    // Generated by scripts/gen-brief-og.mjs via @vercel/og + Geist Regular.
    // Filename per Wiele Image Naming SEO Law: topic-angle-context.
    // Alt text (112 chars) wired in og:image:alt downstream:
    //   "Wiele Citation Brief #001 — Five-Stage Citation Hierarchy for AI
    //    answer engines. Citation, not clicks."
    ogImage:
      "/og/wiele-citation-brief-001-five-stage-citation-hierarchy.png",
    faq: [
      {
        question: "What is a Citation Brief?",
        answer:
          "A Wiele Citation Brief is a single-topic field guide engineered to be cited by AI answer engines. Each brief is extractable, schema-marked, and ties one decision-stage query to one methodology Wiele owns. Briefs are the top-of-funnel asset in the Wiele Citation Score™ subscription.",
      },
      {
        question: "Which AI engines use this methodology?",
        answer:
          "The Five-Stage Citation Hierarchy applies across ChatGPT, Perplexity, Google AI Overviews, Gemini, Microsoft Copilot, Claude, and the emerging answer surfaces. Specific weights vary by engine; the five stages are universal.",
      },
      {
        question: "Is this the same as classical SEO?",
        answer:
          "No. Classical SEO targets blue-link rankings. Answer Engine Optimization (AEO) targets recommendation inclusion inside the answer itself. Wiele engineers both, run as one integrated system — classical SEO compounds AEO and vice versa.",
      },
      {
        question: "How long until a brand starts being cited?",
        answer:
          "Entity-resolution wins land first, typically 30–60 days after Map. Citation-history compounds visibly from month three. The Wiele Citation Score™ tracks lift month over month against a named competitor set.",
      },
      {
        question: "Can Wiele guarantee citation inclusion?",
        answer:
          "No agency can. Citation is probabilistic — engines weigh hundreds of signals. Wiele engineers all five stages so probability tilts decisively toward inclusion, and publishes engine-run methodology so claims are verifiable. See /trust for the standard.",
      },
      {
        question: "What does engagement with Wiele typically look like?",
        answer:
          "Most engagements start with a Signal Audit — a diagnostic that maps the citation graph, entity baseline, authority gaps, and a 30-day roadmap. From there, retainers run on the Map. Build. Compound. rhythm.",
      },
      {
        question: "Is this brief the full methodology?",
        answer:
          "This brief is the framework + applied tactics. Full implementation runs through a Wiele engagement — the Citation Score™ subscription instruments the lift; the Authority Engine retainer executes month-over-month.",
      },
      {
        question: "Who wrote this brief?",
        answer:
          "Jonathan Landman, founder of Wiele Group. Every Wiele brief carries a named author and a review trace at /trust. Founder voice is one of the five citation signals Wiele engineers for.",
      },
    ],
  },
  {
    slug: "stage-3-structured-extractability",
    briefNumber: 2,
    title:
      "Stage 3 — How to engineer pages AI answer engines actually quote",
    summary:
      "Stage 3 of the Five-Stage Citation Hierarchy — Structured Extractability — is the highest-leverage stage. Schema bundle, content pattern, antipatterns, and the Wiele extractability checklist.",
    eyebrow: "AEO methodology",
    category: "AEO methodology",
    author: "Jonathan Landman",
    reviewer: "Jonathan Landman",
    lastUpdated: "2026-05-14",
    readingMinutes: 14,
    ogImage:
      "/og/wiele-citation-brief-002-stage-3-extractability.png",
    faq: [
      {
        question: "What is Stage 3 in the Five-Stage Citation Hierarchy?",
        answer:
          "Stage 3 is Structured Extractability — whether an AI answer engine can pull a clean, attributable answer block off your page. It stacks on Entity Resolution (Stage 1) and Source Authority (Stage 2), and feeds Freshness (Stage 4) and Recommendation History (Stage 5). The full hierarchy is in Citation Brief #001.",
      },
      {
        question: "Which schema types matter most for AI citation?",
        answer:
          "Five do the heavy lifting at Stage 3: Article (the methodology wrapper), FAQPage (the answer-harvester for genuine buyer questions), HowTo (procedural content), Person (named-author authority signal), and BreadcrumbList (structural context). All five should ship as inline JSON-LD, not injected via client-side JavaScript.",
      },
      {
        question: "Should every page have FAQPage schema?",
        answer:
          "Only if the page contains genuine buyer Q&A — eight to ten substantive questions with real answers. FAQPage schema stuffed with marketing fluff (Why choose us? How long until results?) gets flagged by Google's rich-result eligibility filter and silently dropped. Reserve FAQPage for buyer-decision questions with substantive answers; mirror the schema content to the visible content exactly.",
      },
      {
        question: "HowTo vs Article — which should I use?",
        answer:
          "Article wraps any methodology, brief, case study, or thought-leadership piece — it's the editorial wrapper for substantive content. HowTo wraps procedural content where the page documents a sequence of steps or a checklist. A methodology page that walks a buyer through a five-stage process can carry both: Article as the outer wrapper, HowTo for the procedural section.",
      },
      {
        question: "Does the schema have to be in JSON-LD format?",
        answer:
          "Microdata and RDFa work in principle, but every major engine documents JSON-LD first and supports it most reliably. JSON-LD also separates cleanly from rendered content, which makes the schema easier to maintain and harder to break with content edits. Wiele engineers JSON-LD across every engagement.",
      },
      {
        question: "How do I test if my schema is working?",
        answer:
          "Google's Rich Results Test (search.google.com/test/rich-results) is the primary tool — it validates the schema and previews how Google might render it. Schema.org Validator (validator.schema.org) catches structural errors. For an end-to-end check, run a fixed prompt panel against the live engines after the schema ships and compare citation share before and after; that's how the Citation Score™ subscription instruments the lift.",
      },
      {
        question: "Does Stage 3 apply to non-English content?",
        answer:
          "Yes — schema is language-agnostic and the extractability content pattern (definitive opener, semantic heading hierarchy, table-or-list layouts, on-page citations) transfers across languages. Specific engine weights drift slightly between locales, but the structural lift from a Stage 3 sprint shows up consistently across English, French, German, Spanish, and Japanese in the Wiele Citation Tracker dataset.",
      },
      {
        question: "What's the typical citation-share lift from a Stage 3 sprint?",
        answer:
          "Across pre-engagement Signal Audits where Stage 3 was the primary intervention, the typical citation-share lift on Stage-3-sensitive prompts is 30 to 50 percent inside one quarter. The exact lift depends on baseline (sites with no schema and buried answers see the largest delta; sites with partial schema see smaller incremental lift) and competitive context (uncontested verticals lift faster than saturated ones). The Citation Score™ subscription tracks the lift month over month against a named competitor set.",
      },
    ],
  },
];

/**
 * Pre-computed TOC for each brief — extracted from the MDX H2/H3 headings.
 * Slugs match mdx-components.tsx slugify() and rehype-slug behaviour.
 *
 * Empty / absent entry = no TOC sidebar (page wrapper renders single-column).
 * Brief #001 ships without a TOC for visual parity with the pre-refactor page.
 */
export const BRIEF_TOC: Readonly<Record<string, readonly TocEntry[]>> = {};

/* ─────────────────────────────────────────────────────────────
   Public API — runtime-safe (no fs dependency)
───────────────────────────────────────────────────────────────── */

export function getVisibleBriefManifest(): readonly CitationBriefManifestEntry[] {
  return BRIEF_MANIFEST.filter((b) => !b.hidden);
}

export function getBriefBySlug(
  slug: string,
): CitationBriefManifestEntry | undefined {
  return BRIEF_MANIFEST.find((b) => b.slug === slug && !b.hidden);
}

export function getBriefToc(slug: string): readonly TocEntry[] {
  return BRIEF_TOC[slug] ?? [];
}

export function getAllBriefSlugs(): readonly string[] {
  return getVisibleBriefManifest().map((b) => b.slug);
}
